add Function
genepa-yokoyama/workflow-sample pull request #3
Opened 2024-04-26 07:54 UTC by ykyk-314

2024-04-26 09:22 UTC, ykyk-314 commented
コメント追加

2024-04-26 09:25 UTC, genepa-yokoyama requested changes
Reviewer
routes

2024-04-26 09:49 UTC, genepa-yokoyama requested changes
ReviewCommentテスト

2024-04-26 10:07 UTC, genepa-yokoyama requested changes
test

2024-04-30 09:55 UTC, genepa-yokoyama reviewed
PR コメント

2024-04-30 09:55 UTC, genepa-yokoyama commented on .github/workflows/chatwork.yml
xxx
test
```suggestion
  イシューコメント:
    types:
      - created
      - edited

```

2024-04-30 09:59 UTC, merged